sdenec/tidy5e-sheet

lang/pt-BR.json
=> translation pt-BR

lang/pt-BR.json
Minor spelling fixes and corrections regarding the official D&D translation in Portuguese. // Correções de ortografia e adequação à tradução oficial da edição brasileira de D&D.
=> Brazilian Portuguese translation fixes

lang/cs.json
I noticed I mistranslated one term (Czech translation of SRD uses different word for background than I thought) and reworded another term.
=> Minor Czech language changes

styles/tidy5e-sheet.css, templates/actors/npc/parts/tidy5e-npc-traits.html, templates/actors/parts/tidy5e-inventory.html, templates/actors/parts/tidy5e-traits.html, tidy5e-sheet.js
Reverts sdenec/tidy5e-sheet#151
=> Revert "bring master branch up to dnd5e 1.2.0"

styles/tidy5e-sheet.css, templates/actors/npc/parts/tidy5e-npc-traits.html, templates/actors/parts/tidy5e-inventory.html, templates/actors/parts/tidy5e-traits.html, tidy5e-sheet.js
remaking PR because of revert accidents
=> bring sheets up to dnd5e120

src/lang/fr.json
- CurrencyAbbr* (all)
- Search* (all)
- Attunement* (all)
- AbbrSavingThrow
- SpellAttackMod
- PreparedSpells
- PreparedSpellsMax
- SpellSchool
- TIDY5E.AttunementWarning, TIDY5E.AttunementItems and TIDY5E.AttunementMax doesn't work
=> Update french translation

src/lang/es.json
=> Upload es.json

src/lang/ja.json
localisation file provided by `Asami`
=> ja.json update

src/lang/en.json, src/lang/es.json, src/module.json
Updated the unused Spanish loc file to v0.4.25, and modified `module.json` to accept it. Also corrected a small typo in the English file.
Awesome module! 👍
=> Update the Spanish localization file

src/lang/cs.json, src/lang/en.json, src/scripts/app/settings.js, src/templates/actors/parts/tidy5e-traits.html, src/templates/actors/tidy5e-npc-ltd.html, src/templates/actors/tidy5e-sheet-ltd.html, src/templates/actors/tidy5e-sheet.html, src/templates/settings.html
Some missing translations have been added.
Updated CS lang translations to match standard Czech translations.
=> Added missing translations

src/scripts/tidy5e-npc.js
DEFAULT_TOKEN is throwing an exception on my instance.
=> Update reference to use CONST.DEFAULT_TOKEN instead of DEFAULT_TOKEN

module.json
Small whitespace fix in module.json
=> module.json small whitespace fix

src/lang/ja.json
Rolling back ja.json from centralized module as it stopped being the only core localization module.
Future updates will be sent via PRs, sorry for the trouble.
=> rollback ja.json from centralized module

module.json, src/lang/hu.json, src/module.json
Hello!
I really like this module and I thought I'd contribute with a hungarian translation.
Please review, and I hope it can be accepted so my players - and hopefully other hungarian users too - will enjoy the DnD VTT experience more.
=> Add hungarian translation

src/scripts/app/settings.js
fixes #541 by removing deprecated entities reference
=> fixes #541 - Remove deprecated use of entities

module.json, src/module.json, src/scripts/app/ammo-switch.js, src/scripts/app/tidy5e-favorites.js, src/scripts/tidy5e-item.js, src/scripts/tidy5e-npc.js, src/scripts/tidy5e-sheet.js, src/scripts/tidy5e-vehicle.js, src/templates/actors/parts/tidy5e-features.html, src/templates/actors/parts/tidy5e-inventory-footer.html, src/templates/actors/parts/tidy5e-inventory-grid.html, src/templates/actors/parts/tidy5e-inventory.html, src/templates/actors/parts/tidy5e-npc-spellbook.html, src/templates/actors/parts/tidy5e-spellbook-footer.html, src/templates/actors/parts/tidy5e-spellbook-grid.html, src/templates/actors/parts/tidy5e-spellbook.html, src/templates/actors/parts/tidy5e-traits.html, src/templates/actors/tidy5e-npc-ltd.html, src/templates/actors/tidy5e-npc.html, src/templates/actors/tidy5e-sheet-ltd.html, src/templates/actors/tidy5e-sheet.html, src/templates/actors/tidy5e-vehicle-ltd.html, src/templates/actors/tidy5e-vehicle.html
This is a non-backwards compatible update to get Tidy Sheet working with V10 & dnd5e 2.0.0.
=> Update module to be compatible with v10 & dnd5e 2.0.0, does not work with v9

src/scripts/app/exhaustion.js, src/scripts/app/show-actor-art.js, src/scripts/app/tidy5e-favorites.js, src/scripts/tidy5e-npc.js, src/scripts/tidy5e-sheet.js, src/templates/actors/parts/tidy5e-effects.html, src/templates/favorites/item.hbs
=> Update all uses of data to the v10 equivalents

src/scripts/app/exhaustion.js, src/scripts/app/lazyExpAndHp.js, src/scripts/app/lazymoney.js, src/scripts/app/settingsList.js, src/scripts/app/spellClassFilter.js, src/scripts/tidy5e-sheet.js, src/templates/actors/tidy5e-sheet.html
=> Bug fix laxy hp and exp

src/lang/en.json, src/scripts/app/lazyExpAndHp.js, src/scripts/app/lazymoney.js, src/scripts/app/settings.js, src/scripts/app/settingsList.js, src/templates/settings.html
This should be a bug fix for:
- https://github.com/sdenec/tidy5e-sheet/issues/610 
- a module compatiblity with https://foundryvtt.com/packages/link-item-resource-5e
- integration of 'Lazy Money' with module 'World Currency']
=> Bug fix https://github.com/sdenec/tidy5e-sheet/issues/610

src/scripts/app/lazymoney.js
Bug fix laxymoney again for bug fix https://github.com/sdenec/tidy5e-sheet/issues/616
=> Bug fix lazy money again

src/css/tidy5e.css, src/templates/actors/tidy5e-npc.html
=> Fix for missing Creature Size and NPC HP Editing

src/templates/actors/tidy5e-npc.html, src/templates/actors/tidy5e-sheet.html
Fixes javascript error "Uncaught TypeError: event.currentTaret.closest(..)" is null #752
=> fix: :bug: add data-key to sheets

src/css/tidy5e.css, src/templates/actors/parts/tidy5e-traits.html, src/templates/actors/tidy5e-npc.html, src/templates/actors/tidy5e-sheet.html
Fixes for:
Cannot roll skill checks #752
Cannot change skill check proficiency
No tools listed under Tool Proficiency #760
=> Fix for D&D 2.2.1

src/css/tidy5e.css, src/scripts/app/tidy5e-favorites.js, src/scripts/tidy5e-sheet.js
Proper Effect should be:
`flags.tidy5e-sheet.maxPreparedSpells` CUSTOM formula, ex. `max(1, floor(@classes.wizard.levels + @abilities.int.mod))`
=> Fixes for maxPreparedSpells and other Issues

src/lang/de.json
Sorry, only now spotted a typo/word fragment I left while updating the translation. 🙏
=> German translation fix

src/module.js, src/templates/actors/tidy5e-npc.html, src/templates/actors/tidy5e-sheet.html
Removed Ini patching.
Removed max length and data-dtype on the Ini mod input to allow for valid non-number inputs, which can be longer than 2 characters.
=> [#714] Fixed Ini NaN mod issue
