module.json, styles/darkmode/tidy5e-darkitems.css, styles/tidy5e-items.css, styles/tidy5e-modules.css, tidy5e-item.js
Resolves #88 
Tidy Sheet has been modifying the styles of the default 5e Item sheet. This does not allow GMs to choose the default item sheet if they desire to without disabling the Tidy Sheet module itself.
It also opens up the door for a lot of inter-module conflicts. Instead we should register the Tidy 5e Item sheet as a different ItemSheet option, and set it to be the default when we do so.
Tested with Windows Client Foundry VTT 0.6.6.
=> Split Item Sheet into its own Sheet

tidy5e-item.js
Resolves #94 
- use the hooks in BetterRolls to register the Tidy 5e Item Sheet so that Better Rolls tab appears
- fix my previous usage of tabs instead of spaces on this file. It looks like spaces is the convention elsewhere (whoops, sorry)
=> support better rolls item sheet

styles/darkmode/tidy5e-darksheet.css, styles/tidy5e-sheet.css
These CSS changes allow other modules to make individual inputs that use "contenteditable=true" read-only while still looking good (ex. https://github.com/illandril/FoundryVTT-sheet5e-lockdown v2.0.0).
=> Make it easier for other modules to configure editability of individual inputs

styles/tidy5e-sheet.css, templates/actors/npc/parts/tidy5e-npc-traits.html, templates/actors/parts/tidy5e-inventory.html, templates/actors/parts/tidy5e-traits.html, tidy5e-sheet.js
These changes are backwards compatible with dnd5e 1.1.0.
- Swaps Senses out for something leveraging the default picker on both NPC and PC sheets.
- Fix Attunement class and icon appearance. `item.data.attuned` was removed for `item.data.attunement` which is 1, 2, or 3 where `3 === attuned`.
I looked at the Item Sheet, and since all tidy is doing is css changes that has no changes needed.
=> bring master branch up to dnd5e 1.2.0

.github/workflows/main.yml
Source: [League of FoundryVTT Developers module template](https://github.com/League-of-Foundry-Developers/FoundryVTT-Module-Template). There is a guide with pictures on that readme for how to use this.
Inspiration: [Package Releases and Version History](https://foundryvtt.wiki/en/development/guides/releases-and-history).
This PR will add a Github Action workflow that will only run when you create a release on the GH UI. The action will replace your module.json's `manifest` and `download` urls with the correct values based on the tag input, and then zip up the module files and attach them to the release.
This enables people who desire to install a past version of tidy-5e an easy way to do so without you having to store each version's zip in the repo itself.
=> add release workflow

src/lang/de.json
Added `TIDY5E.Settings.ShowTraitLabels` and improved a few other translations. Attunement is now translated as it is in the german sourcebooks, and for `edit` the same translation is used everywhere for consistency instead of two different synonyms.
**Things missing translation keys:**
- The new `Attuned items` indicator (sun icon in the bottom left corner of inventory screen) with its tooltip(s)
-  [tidy5e-favorites.js#L346](https://github.com/sdenec/tidy5e-sheet/blob/eb4c7cb20de2a3693e077be8b704caf60cf66589/src/scripts/app/tidy5e-favorites.js#L346) - maybe there's more similar cases? Haven't looked yet.
- Abbreviations for currency in inventory (`CP` should be `KM` in german, for example)
Thanks for Tidy5ESheet, our group loves it 🎉
=> Update german locale for 0.4.x

src/_scss/partials/_general.scss, src/_scss/partials/_tabs.scss, src/css/tidy5e.css
Scrollbars are not showing properly in Firefox (screenshots below).
Without overflow:
With overflow:
Due to the lack of support for **::-webkit-scrollbar-thumb** in Firefox (more info in [this post](https://stackoverflow.com/questions/6165472/custom-css-scrollbar-for-firefox)), I've made a quick fix to hide the scrollbar when there is no overflow and give it a better look when there is overflow:
=> Fixed scrollbars in Firefox

src/scripts/tidy5e-sheet.js, src/templates/actors/parts/tidy5e-inventory-footer.html, src/templates/actors/tidy5e-npc.html, src/templates/actors/tidy5e-sheet.html
This resolves an issue with GM Screen:
https://github.com/ElfFriend-DnD/foundryvtt-gmScreen/issues/91
Since it is possible to have multiple of the same actor sheet open while using GM Screen, `actorId` can't be relied upon to be unique for the purposes of html ids. This was causing problems with a few inputs on the Tidy Sheet, though only inspiration was reported.
I've tested this with 0.8.7.
=> use appId instead of actorId for guaranteed uniqueness

src/lang/en.json, src/scripts/app/settings.js, src/scripts/app/settingsList.js, src/scripts/tidy5e-sheet.js, src/templates/actors/parts/tidy5e-inventory.html, src/templates/settings.html
I wanted my players to be able to easily switch the ammo for their weapons directly from inventory, so I've added a simple selector to do that. This way they don't need to open the item editor and find the ammunition field to change it.
Use Case: The player has several types arrows (regular, fire, +1, etc.) and they would like to switch back and forth between the different types.
=> Add selector for switching ammo on ranged weapons

src/scripts/app/ammo-switch.js, src/scripts/tidy5e-npc.js, src/templates/actors/parts/tidy5e-features.html
Hi,
Simple PR.
Adding ammo dropdown to NPCs and making sure we retrieve the synthetic actor instead of the original actor if the sheet originates from an unlinked token.
=> Add ammo dropdown to NPCs

src/_scss/partials/_inventory.scss, src/css/tidy5e.css, src/scripts/tidy5e-npc.js, src/templates/actors/parts/tidy5e-features.html
Hi,
First, I realize that it was more a feature than a bug :)
But I feel that NPC's equipments need uses & actions. Especially for magic items and such.
This PR has two commits:
**First commit:**
- Add uses and actions to NPC's equipment
- Sort NPC's equipment:
-- "Equipments" first, as these are usually where magic items fall in.
-- Then "ammunition", then the rest.
-- I feel that in the heat of a combat, it's more intuitive for the GM to have these two categories at the top of the inventory section.
-- Also, I added that specific order because it is very difficult for a GM to manually order items in the inventory section. The way items are divided at runtime makes it so, that some items in the inventory are virtually impossible to put first in the inventory list.
**Second commit:**
- …
=> Feat npcs uses actions

src/lang/de.json, src/lang/en.json, src/scripts/app/settings.js, src/scripts/app/settingsList.js, src/scripts/tidy5e-npc.js, src/scripts/tidy5e-sheet.js, src/scripts/tidy5e-vehicle.js, src/templates/settings.html
I personally use a lot of modules, that add stuff to the title bar of the sheets, which causes some actions (especially the close) to disappear, unless I resize the sheet (everytime).
To work around this, I added settings to configure the width of the npc, player and vehicle sheets.
The settings are user based settings, so every player can set it up themselves, with the default value of 740
=> Sheet width config

module.json
The latest Core version number is `9` not `0.9.9`, so Foundry reports this module as incompatible since `0.9.9 < 9`. Core has switched to a new versioning scheme using whole number version numbers. Now `0.8.x` is retroactively v8, and the latest version is v9, the next version will be v10. New Core releases do also have a build number, and this can be specified if needed like so: `9.242` indicating Core v9, build 242 (the latest released version as of now). However, the build specificity isn't necessary in most cases, so for this PR it is omitted.
Resolves #473
=> Update compatibleCoreVersion to "9"

src/scripts/tidy5e-sheet.js
I noticed that when adding bonuses to an actor's spell attack modifier (for example, if they had the Robes of the Archmagi equipped), they didn't get reflected in the display. This PR simply adds the ranged spell attack modifier to the display so that it properly displays on the sheet.
Caveat: Unfortunately, it seems that Foundry differentiates `rsak` and `msak` for ranged and melee spell attack bonuses respectively, but doesn't have any accessible field for a more general spell attack bonus. Thus, I defaulted to the _ranged_ spell attack modifier which may not be correct/desired behavior in all cases.
=> Updating "Attack Mod" field to account for spell attack modifier bonuses

src/templates/actors/parts/tidy5e-npc-spellbook.html, src/templates/actors/parts/tidy5e-spellbook.html
Concentration and Ritual components weren't getting their usual different "block" background as an highlight. This fixes the issue.
=> Fixed different background for C and R spell components

src/templates/actors/tidy5e-sheet.html
This matches the functionality of the base dnd5e sheet, improving
visual parity when switching between the two.
Closes #532.
=> Disable background text field if background item present

.gitignore, .vscode/extension.json, .vscode/settings.json, module.json, src/module.json, src/scripts/tidy5e-item.js, src/scripts/tidy5e-npc.js, src/scripts/tidy5e-sheet.js, src/scripts/tidy5e-vehicle.js
These changes are sufficient to enable the module to work on v10 and the dnd5e 2.0.0 release as far as I can tell, but they still rely heavily on the compatibility shims. Further updates can remove usage of deprecated code before v11.
=> Preliminary v10 (dnd5e 2.0.0) update

src/scripts/tidy5e-sheet.js
checkDeathSaveStatus is attempting to search the sheet's html using a raw jquery `$` rather than html.find, meaning that it would fail when the rendered html was not in the same window (such as when the character sheet is popped out). 
This fixes the "dead" class not being applied when HP is reduced to zero on a popped-out character sheet window.
=> fix checkDeathSaveStatus html find

src/lang/de.json
These changes translate all new keys up to the most recent Tidy5E version, minus settings.
=> Update german translation

src/styles/partials/_main-tab.scss
This is a small fix for a layout issue with the tool proficiency section.
With this, that section now looks like this:
Fixes https://github.com/sdenec/tidy5e-sheet/issues/781. Build and tested locally, tried to keep the CSS as specific as possible so this should not impact anything else.
=> Fix tool proficiency layout

src/module.json, src/scripts/app/tidy5e-actor-origin-summary-config.js, src/scripts/app/tidy5e-context-menu.js, src/scripts/app/tidy5e-exhaustion.js, src/scripts/tidy5e-item.js, src/styles/_items.scss, src/styles/partials/_character-details.scss, src/templates/actors/parts/tidy5e-effects.html, src/templates/actors/parts/tidy5e-features.html, src/templates/actors/parts/tidy5e-origin-summary-config.html, src/templates/actors/tidy5e-npc.html, src/templates/actors/tidy5e-sheet.html
#797
Makes numerous adjustments for dnd5e compatibility.
1. Fixed item accordion styles
2. Fixed item source styles
3. Made Race and Background read-only in the Origin Summary dialog when their respective item is present in the Features tab
4. Added creature type to Player Character sheet
5. Resolved deprecation warnings as discovered
6. Updated min system compatibility to 2.4.0 since there are breaking changes in the 2.4 update
=> [#797] dnd5e 2.4.0 compatibility updates
